Net/ThemeName "adw-gtk3-dark"
Gtk/ThemeName "adw-gtk3-dark"
Gtk/ApplicationPreferDarkTheme 1
Net/IconThemeName "Papirus-Dark"
Net/SoundThemeName "ocean"
Gtk/CursorThemeName "Bibata-Modern-Ice"
Gtk/CursorThemeSize 24
Gtk/FontName "Inter 10"
Gtk/DecorationLayout "icon:minimize,maximize,close"
Gtk/EnableAnimations 1
Gtk/PrimaryButtonWarpsSlider 1
Gtk/ToolbarStyle 3
Gtk/MenuImages 1
Gtk/ButtonImages 1
Gdk/WindowScalingFactor 1
Net/CursorBlink 1
Net/CursorBlinkTime 1000
Net/EnableEventSounds 0
Net/EnableInputFeedbackSounds 0
Xft/Antialias 1
Xft/Hinting 1
Xft/HintStyle "hintslight"
Xft/RGBA "rgb"
